version: '3'
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MID=${UID}
      - MGID=${GID}

networks:
  default:
    name: infra
    external: true
