FROM spark-submit:latest

COPY requirements.txt /app/
RUN cd /app \
      && pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt


COPY submit.sh /submit.sh

COPY main.py /app/app.py

ENV SPARK_APPLICATION_PYTHON_LOCATION /app/app.py
CMD ["/bin/bash", "/template.sh"]